version: '3.8'


services: 
  app:
    build: ./infra/php
    volumes:
     - ./backend:/work
 #テスト
  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work



  db:
    #Docker HubからMySQL5.7の公式イメージを引っ張ってくる設定です。
    image: mysql:5.7
    # コンテナ名を指定しています。
    container_name: laravel_db
    # MySQLのコンテナ内の環境変数を指定しています。任意のものを設定してください。
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      TZ: 'Asia/Tokyo'
    # 起動時のコマンドになります。
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # ディレクトリの同期をしています。ここを書かないとコンテナを閉じたときにデータベースからデータがなくなるので注意してください。詳しくはdocker 永続化などと調べると良いかもです。
    volumes:
      - ./infra/DB/volume:/var/lib/mysql
      - ./infra/DB/my.cnf:/etc/mysql/conf.d/my.cnf
    # ホストの13306番ポートとコンテナのなかの3306番ポートとつなげる設定です。
    ports:
      - 13306:3306


  phpmyadmin:
    #コンテナ名を決めています。
    container_name: phpmyadmin
    #DockerHubからphpmyadminのイメージを引っ張ってくる設定です。
    image: phpmyadmin/phpmyadmin
    #phpmyadminの環境変数の設定です。MySQLの設定を参照して記載してください。PMA_HOSTSにはservicesのdbを指定しています。
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 5000:80